### ISSUE TITLE
refactor: Sequential renderer initializing

### ISSUE THREAD

**Issue by ghost** [arhat-dev/dukkha#105]
Renderers are discovered in map, they are not ordered in golang, for complex initialization (e.g. second renderer uses first renderer to initialize)

```yaml
renderers:
- name: http:foo
- name: http:bar
  config@http:foo: http://example.com/bar-config.yml
```
