### ISSUE TITLE
bug(tasks|hooks): Hook actions skiped for the first run

### ISSUE THREAD

**Issue by donorp** [arhat-dev/dukkha#110]
From krew-index repo:

```
workflow:run:
- name: index-kubectl-convert
  env: *env
  matrix@file: *matrix
  hooks:
    after:matrix:success:
    - shell: mkdir -p build/manifests
    - shell@file?str|template?str: templates/shell/write-blob-entry.tmpl
    after:success:
    - shell@file?str|template?str: templates/shell/write-manifest.tmpl

  jobs:
  - task@template: golang:build({{ env.APP }})
```

action `- shell@file?str|template?str: templates/shell/write-blob-entry.tmpl` was skipped when there was no `build/manifests` dir
