### ISSUE TITLE
Plan for package manager support

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/dukkha#21]
Support package installation on multiple platforms using different package manager

Package manager can be detected by command like `command -v apt-get`, the configuration would be like:

```yaml
packages:install:
- name: <name>
  apt:
  - <package-name-with-version>
  dnf: []
  apk: []
  brew: []
```

**Comment by jeffreystoke** [comment]
another way it to support it using separate tools, which I believe is better:

```yaml
apt:install:
- name: <name your bundle>
  packages:
  - <package-name-with-or-without-version>

dnf:install:
- name: <name your bundle>
  packages:
  - <pakcage-name-with-or-without-version>
```
