### ISSUE TITLE
Allow non-string value for yaml fields using rendering suffix

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/dukkha#33]
Current implementation is expecting string value for rendering suffix:

```yaml
foo@<renderer>: |-
  value: not highlighted
  always: treated as string
```

It should be easy to provide native yaml experience with rendering suffix, just change a few lines in field.BaseField should give us:

```yaml
foo@<renderer>:
  editor: happy
  to:
  - use: { rendering: 0, suffix: 1 }
```
