### ISSUE TITLE
feat: Add git support

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/dukkha#34]
```yaml
# clone a repo to local
git:clone:
- name: example
  url: https://example.com/repo.git
  path: ./third_party/repo
  branch: v0.1.0
  depth: 1

# switch to some branch and always go back to current branch
git:switch:
- name: example
  branch: gh-pages
```
