### ISSUE TITLE
feat: Add github-cli support

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/dukkha#36]
https://github.com/cli/cli

docs: https://cli.github.com/manual

```yaml
github-cli:release:
- name: example
  tag: ${GIT_TAG}
  draft: true
  pre_release: true
  title: ""
  notes: ""
  files:
  - changelog.txt
```
