### ISSUE TITLE
feat: Add `workflow:run` special tasks to compose tasks

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/dukkha#38]
Task to compose other tasks

```yaml
workflow:run:
- name: foo
  jobs:
  - name: job1
    task: buildah:bud(dukkha)
  - name: job2
    shell: git clone
  - name: job3
    shell: 
```
