### ISSUE TITLE
Task hooks: Support task parameters to customize hook execution

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/dukkha#46]
The implementation will be in function call style

```yaml
hooks:
  before:
  - task: buildah:bud(dukkha, {kernel: linux, arch: amd64})
```
