### ISSUE TITLE
feat: Support shell evaluation in env renderer

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/dukkha#47]
This is a common use case to only customize some part of the config using output of shell script

```yaml
image_names@env:
- image: foo:$(git describe --tags -C /path/to/foo/src)-${MATRIX_ROOTFS}-${MATRIX_ARCH}
  manifest: foo:$(git describe --tags -C /path/to/foo/src)-${MATRIX_ROOTFS}
```
