### ISSUE TITLE
Support github workflow matrix generation

### ISSUE THREAD

**Issue by ghost** [arhat-dev/dukkha#72]
Github workflow matrix can be configured to use data from other jobs: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson

An example: https://github.com/docker-library/ruby/blob/master/.github/workflows/ci.yml

When this feature is added, we can define matrix in dukkha for github

```yaml
buildah:build:
- name: foo
  matrix: &matrix
    kernel: [linux]
    arch: [amd64, arm64]

github:generate-workflow-matrix:
- name: foo
  matrix: *matrix
```

and use it directly in github workflow

```yaml
name: build
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    # setup dukkha
    - id: set-matrix
      run: dukkha github local generate-workflow-matrix foo

  run:
    needs: generate
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate.outputs.matrix) }}
    steps:
    # setup dukkha and necessary tools
    - run: ${{ matrix.run-dukkha }}
```
