### ISSUE TITLE
feat(renderer): Support patching during rendering process

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/dukkha#94]
Ability of patching resolved data is convenient for config reusing

Patch support is achieved by adding `!` suffix to existing renderer

```yaml
foo@echo!: # ...
bar@echo!|env: # ...
```

Then the yaml value is expected to be:

```yaml
foo@echo!:
  value: # (any) value for foo
  merge: # (any) value for foo, but will be merged into `value` field
  patch: # (list) rfc6902 patch list
  unique: # (bool) when `value` is a list, ensure elements are unique
```

### Merge

Sample config

```yaml
# filename: foo.yaml
foo@echo!:
  value:
    a:
      b: c
  merge@file: bar.yaml
```

```yaml
# filename: bar.yaml
a:
  c: d
b: c
```

Expected result:

```yaml
foo:
  a:
    b: c
    c: d
  b: c
```

### Merge

Sample config

```yaml
# filename: foo.yaml
foo@echo!:
  value: [foo]
  merge@file: bar.yaml
```

```yaml
# filename: bar.yaml
- bar
```

Expected result:

```yaml
foo:
- foo
- bar
```

## Considerations

- [ ] Do we make sure elements in merged list unique? If so, how? (additional `__unique: true` field to control?)
  - [ ] what if elements are not scalar types? (implement something like assert.EqualValues but only for exported fields?)
- [ ] How do we support standard json-patch (RFC6902, RFC7386)
  - https://github.com/evanphx/json-patch
  - additional `__patch:` field ?

**Comment by jeffreystoke** [comment]
Recursive patching?

```yaml
# filename: foo.yaml
foo@echo:
  data:
    a:
      b: c
  __merge@file: bar.yaml
```

```yaml
# filename: bar.yaml
data:
  b: c
__merge@file: woo.yaml
```

```yaml
# filename: woo.yaml
a:
  c: d
```

Expected result:

```yaml
foo:
  a:
    b: c
    c: d
  b: c
```
